# Generated by Django 5.0.6 on 2024-06-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grooming", "0002_availability_grooming_pet_rename_usuario_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
